services:
  # nginx:
  #   container_name: nginx
  #   build:
  #     context: .
  #     dockerfile: /docker/local/nginx/Dockerfile
  #   volumes:
  #     - ./docker/local/nginx/conf:/etc/nginx/conf.d
  #   ports:
  #     - '80:80'

  # web:
  #   container_name: github-web
  #   build:
  #     context: .
  #     dockerfile: /docker/local/node/Dockerfile
  #   volumes:
  #     - './web:/web'
  #     - 'github-vendor:/web/node_modules'
  #   ports:
  #     - '5173:5173'

  # api:
  #   container_name: github-api
  #   build:
  #     context: .
  #     dockerfile: /docker/local/php-fpm/Dockerfile
  #   volumes:
  #     - './api:/api'

  mongo:
    container_name: mongodb
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
      - ./docker/local/mongodb/init.d:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: system

volumes:
  mongodb: